# Generated by Django 2.2.4 on 2019-08-23 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0002_auto_20190823_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nps',
            name='id',
        ),
        migrations.AlterField(
            model_name='nps',
            name='name',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.Nps')),
            ],
        ),
    ]
