# Generated by Django 2.2.4 on 2019-08-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0003_auto_20190823_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='nps',
            name='now',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
