# Generated by Django 2.2.4 on 2019-08-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0005_nps_past'),
    ]

    operations = [
        migrations.AddField(
            model_name='nps',
            name='rate',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
